### PR TITLE
Addresses #143 (Custom directives to support the JIRA structure macro)

### PR DESCRIPTION
**Pull request by cstarner**
Adds a jira and jira_issue directive to act as a wrapper to the JIRA
structured macro available in Confluence.

Allows for configuring sets of named JIRA servers, not providing servers
at all, and a combination of named servers and overriding their
respective values on the directives.

Provides support for both single issue links (via jira_issue) and JQL
links (via jira). Allows for specifying the parameters available to
the macro.

Allows the directives to be disabled via the 'confluence_adv_restricted_macros'
configuration value

Signed-off-by: Colin Starner <colin.starner@gmail.com>

### CODE REVIEW

**Comment by cstarner** [comment]
@jdknight Is there anything else I need to do, that's preventing this from being merged? I understand the speed of OSS projects, just want to make sure I'm not blocking progress somehow

**Comment by jdknight** [comment]
@cstarner, there is nothing major at this time preventing this pull request being merged. For features that I have the opportunity to merge in which introduce non-trivial changes, I usually like to take the time to setup a test environment and provide a second verification of its capabilities. For this case, I will be planning to spawn up JIRA instances and verify Confluence instances properly generated links (at least between the older supported Confluence revision and the newest).

The main delay though right now is that my next feature I was in the middle of testing was #199 which requires building a setup to verify SSO capabilities (which #234 may sneak in). When testing, it is when #229 was noticed which (IMHO) became a much more high-priority item to address. Unfortunately the lack of solution (for #229) has delayed my own efforts (disheartened) in trying to catch up of new features/maintenance. A more realistic timeline (with respect to time I can contribute to this project) would be that I will optimistically wait to see if a solution arises for #229 until sometime early November, only to find that the limitation with the new Confluence implementation are what they are, followed by a re-work of translator capabilities in the extension to support the legacy translation support a newer (and more limited) translator support (probably wrapping up somewhere near the end of November). After that, I would the continue back to testing and approving pull requests (tweaking where needed; assuming that requests are generally sane and have fulfilled at least the DCO requirement) to clean up the queue before the end of this calendar year.

Sorry for the lack of feedback though. Changes are welcome. I will go through the list of existing pull requests now (include this one), provide a quick review on the components and label them as "planned-end-of-year" for now.

**Comment by jdknight** [comment]
_(template-like response)_ Changes in this pull request look to be in good state. Delays in other features in this project will result in this feature being delayed (see [this comment](https://github.com/sphinx-contrib/confluencebuilder/pull/215#issuecomment-541268554) for more details), so the expected window for this feature is planned around end-of-year (2019). Feel free to make additional changes/etc. to this pull request before the planned window. Critical changes may occur on master before this pull request is merged in -- while you are free to help synchronize features as conflicts are detected, I do mind help correcting conflicts myself when I have the opportunity to merge this change in. If you wish to review changes I may stack on this pull request set, feel free to indicate so. When the window to merge this in this pull requests occurs and changes are needed, I can stack on change and wait for your additional approval. Otherwise, I will assume I may stack changes (if needed) which is deemed best for this extension for a quicker integration into master. Labeling this pull request as "planned-end-of-year".

A quick review of this pull request include the following:
- `CHANGES.rst` should not have been modified (as per [`CONTRIBUTING.rst`](https://github.com/sphinx-contrib/confluencebuilder/blob/master/CONTRIBUTING.rst)); however, I have no problem adjusting options to use proper restructuredText and lexicographical sorted the feature reference when merging in.
- I am hesitant to start references supported directive types inside `README.rst`. I would feel it would be better to be located inside the Documentation instead (a page after "markup"). I will take the contents provided in this pull-requests `README.rst` changes, tweak formatting, Jira casing, etc. and place it in the documentation. You are free to attempt to tweak that ahead of time, but I do not mind doing this myself.
- This extension does not stack (group) imports on single lines (for maintenance reasons).
- Directives like `JIRABaseDirective` may be replaced with a style such as `JiraBaseDirective`.
- Expected output can be tabbed content for easy-of-view as the output verification has relaxed whitespace checking.
- `confluence_jira_servers` should not be initialized in the global configuration call (`prepareConfiguration`).

**Comment by jdknight** [comment]
@cstarner, here we go! Merging into `master`; will be available in next stable release. Thanks for the feature submission.

**Pull request merged**
